version: '3'
services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgrespassword
  redis: 
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      # where to look for Dockerfile.dev
      context: ./server
    volumes:
      # to ignore node modules
      - /app/node_modules
      # to use local server dir in the app dir of container
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379